site_name: UVMS documentation
site_url: https://focusfish.github.io/
plugins:
  - macros
  - mike
  - search
extra:
  version:
    provider: mike
    alias: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/FocusFish
      name: Source on GitHub
  uvms_version: 4.3.4
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
nav:
  - Home: index.md
  - Install UVMS:
    - installation/index.md
    - Manual (recommended): installation/manual.md
    - Docker: installation/docker.md
  - Configure UVMS: configuration/index.md
  - Reference:
    - reference/index.md
    - Audit: reference/audit.md
    - Asset: reference/asset.md
    - Config: reference/config.md
    - Exchange: reference/exchange.md
    - Incident: reference/incident.md
    - Movement: reference/movement.md
    - Movement-Rules: reference/movement-rules.md
    - Spatial: reference/spatial.md
    - Web Gateway: reference/web-gateway.md
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - search.suggest
    - search.highlight
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: light blue
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
